/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Biblioteka */

#ifndef _Included_Biblioteka
#define _Included_Biblioteka
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Biblioteka
 * Method:    click
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Biblioteka_click
  (JNIEnv *, jclass, jint);

/*
 * Class:     Biblioteka
 * Method:    autostart
 * Signature: (ZZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Biblioteka_autostart
  (JNIEnv *, jclass, jboolean, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
