/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Biblioteka */

#ifndef _Included_Biblioteka
#define _Included_Biblioteka
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     Biblioteka
	* Method:    click
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_Biblioteka_click
		(JNIEnv *, jclass, jint);

	/*
	* Class:     Biblioteka
	* Method:    autostart
	* Signature: (ZZLjava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_Biblioteka_autostart
		(JNIEnv *, jclass, jboolean, jboolean, jstring);

	/*
	* Class:     Biblioteka
	* Method:    CzyAutostart
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_Biblioteka_CzyAutostart
		(JNIEnv *, jclass);

	/*
	* Class:     Biblioteka
	* Method:    runAsRoot
	* Signature: (Ljava/lang/String;Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_Biblioteka_runAsRoot
		(JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif


