/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_Start */

#ifndef _Included_test_Start
#define _Included_test_Start
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_Start
 * Method:    kwadrat
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_test_Start_kwadrat
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
